### PR TITLE
ignore invalid properties

### PR DESCRIPTION
**Pull request by khoinguyenc8y**
give it a possibility to ignore invalid properties (e.g. different type)

### CODE REVIEW

**Comment by fforw** [comment]
I have to go with a big "nope" on this one.
Just ignoring invalid properties is bad in my opinion. It goes against the behavior of the lib.

Now making it optional improves that somewhat, but the way this is done, with https://en.wikipedia.org/wiki/Coding_by_exception is an absolute nono.

The way to do something like this would be to make the class extend org.svenson.AbstractDynamicProperties and make all "valid" properties to bean properties. This way all the "valid" properties are accessible as normal properties and the "invalid" ones are written as dynamic properties

**Comment by khoinguyenc8y** [comment]
> I have to go with a big "nope" on this one.
> Just ignoring invalid properties is bad in my opinion. It goes against the behavior of the lib.
> 
> Now making it optional improves that somewhat, but the way this is done, with https://en.wikipedia.org/wiki/Coding_by_exception is an absolute nono.
> 
> The way to do something like this would be to make the class extend org.svenson.AbstractDynamicProperties and make all "valid" properties to bean properties. This way all the "valid" properties are accessible as normal properties and the "invalid" ones are written as dynamic properties

Well, we do extends the AbstractDynamicProperties, however we don't want to lose the strong type in our properties (which could need another round of converting between hash map to expected type).

Would you be fine with following changes?

`Class<?> propertyType = propertyInfo.getType();
boolean validType = propertyType != null && value != null && propertyType.isAssignableFrom(value.getClass());
if(validType || !cx.target.getClass().isAnnotationPresent(IgnoreOnInvalidProperties.class)) {
    propertyInfo.setProperty(cx.target, value);
}`

**Comment by fforw** [comment]
>  however we don't want to lose the strong type in our properties
I'm not sure I understand this. The normal bean properties in AbstractDynamicProperties *are* strongly typed.

Not sure the alternate code is correct. There is some amount of conversion involved so `propertyType.isAssignableFrom(value.getClass())` might not be true. It still seems overly intrusive a change for such a rare use-case.

**Comment by khoinguyenc8y** [comment]
Just to show what I was trying to say, I wrote a small test:
Screenshot 2019-05-15 at 16 02 27
The type of the property would be HashMap instead of Bean. That's why we wanted to have it as direct bean property instead.

And with direct property, while we are parsing a collection (or a bean that contains collection of other beans) from JSON string (e.g. from a server which was populated by different users), if one contains an invalid type in property, the parsing would be failed and we don't know actually which one was invalid.

**Comment by fforw** [comment]
Yes, "propertyBean" would be parsed as Map in this scenario, but it also would be an example of an "invalid"/secondary/dynamic property

```java
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.svenson.AbstractDynamicProperties;
import org.svenson.JSONParser;

import java.util.Map;

import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.Matchers.*;

public class ParseTest
{
    private final static Logger log = LoggerFactory.getLogger(ParseTest.class);


    @Test
    public void parseDynanicBean()
    {
        DynamicBean dynamicBean = JSONParser.defaultJSONParser().parse(DynamicBean.class,
            // language=JSON
            "{\n" +
                "    \"innerBean\" : {\n" +
                "        \"value\" : \"Value for inner bean\"\n" +
                "    },\n" +
                "    \"otherProp\" : {\n" +
                "        \"value\" : \"Value in a map\"\n" +
                "    }\n" +
                "}"
        );


        assertThat(dynamicBean, is(notNullValue()));
        assertThat(dynamicBean.getInnerBean().getValue(), is("Value for inner bean"));

        assertThat(dynamicBean.getProperty("otherProp"), is(instanceOf(Map.class)));
        assertThat(((Map)dynamicBean.getProperty("otherProp")).get("value"), is("Value in a map"));

    }

    public static class DynamicBean extends AbstractDynamicProperties
    {
        private InnerBean innerBean;


        public InnerBean getInnerBean()
        {
            return innerBean;
        }


        public void setInnerBean(InnerBean innerBean)
        {
            this.innerBean = innerBean;
        }
    }

    public static class InnerBean
    {
        private String value;


        public String getValue()
        {
            return value;
        }


        public void setValue(String value)
        {
            this.value = value;
        }
    }
}
```

**Comment by khoinguyenc8y** [comment]
We have complex types that extend AbstractDynamicProperties and get them parsed by some convention in property name / alias so we could have "strong" type of them instead of trying to convert them from a Map again. That's the best benefits that we can have from AbstractDynamicProperties.

Anyway, if this is a "big no" for you, I'll delete the branch.

**Comment by fforw** [comment]
Still feels wrong.

**Pull request closed without merging**
