### PR TITLE
Refactor property accessors 

### PR DESCRIPTION
**Pull request by jaroslawherod**
Hi,
I've made some refactor :
- Removed obsolete IDE files
- Provide an abstraction for property accesor's 
- Update source level to JDK 7 
- Add Java Microbenchmark 

Test executed at :
- JDK :
openjdk version "1.7.0_201"
OpenJDK Runtime Environment (Zulu 7.25.0.5-linux64) (build 1.7.0_201-b02)
OpenJDK 64-Bit Server VM (Zulu 7.25.0.5-linux64) (build 24.201-b02, mixed mode)

- Hardware:
  Cpu: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz  
  Memory:   16 GB 

Before changes:

| Benchmark        |    (items) |  (nested) |    (scenario) |   Mode | Cnt |       Score |   Error |  Units |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| BenchMark.generator |        1 |         1 |         PLAIN |  thrpt |    2 |  863348.956 |   |      ops/s |
| BenchMark.generator |        1 |         1 |  TYPE_CONVERT |  thrpt |    2 |  395722.295 | |          ops/s |
| BenchMark.generator |        1 |        2 |         PLAIN |  thrpt |    2 |  466647.410 | |          ops/s |
|BenchMark.generator |        1 |         2 |  TYPE_CONVERT |  thrpt |    2 |  207760.465 | |          ops/s |
 |BenchMark.generator |       10 |         1 |         PLAIN |  thrpt |    2 |  220311.730 | |          ops/s |
 |BenchMark.generator |       10 |         1 |  TYPE_CONVERT  | thrpt |    2 |  165988.655  | |         ops/s |
 |BenchMark.generator |       10  |        2 |         PLAIN  | thrpt |    2 |  114646.952 | |          ops/s |
 |BenchMark.generator |       10  |        2 |  TYPE_CONVERT |  thrpt |    2  |  85513.540  | |         ops/s |
 |BenchMark.parser |           1  |        1  |        PLAIN  | thrpt  |   2  | 496612.341   | |        ops/s |
 |BenchMark.parser  |          1  |        1 |  TYPE_CONVERT  | thrpt |    2 |  235037.167  | |         ops/s |
 |BenchMark.parser |           1 |         2 |         PLAIN |  thrpt |    2 |  255616.988  | |         ops/s |
 |BenchMark.parser |           1 |         2  | TYPE_CONVERT |  thrpt |    2 |  119621.954  | |         ops/s |
 | BenchMark.parser | 10 | 1 | PLAIN | thrpt | 2| 158485.708 | | ops/s
 | BenchMark.parser | 10 | 1 | TYPE_CONVERT | thrpt | 2| 114129.189 | | ops/s
 | BenchMark.parser | 10 | 2 | PLAIN | thrpt | 2| 80118.343 | | ops/s
| BenchMark.parser | 10 | 2 | TYPE_CONVERT | thrpt | 2| 55888.000 | | ops/s

| Benchmark        |    (items) |  (nested) |    (scenario) |   Mode | Cnt |       Score |   Error |  Units |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| BenchMark.generator | 1 | 1 | PLAIN | thrpt | 2| 999452.160 | | ops/s
| BenchMark.generator | 1 | 1 | TYPE_CONVERT | thrpt | 2| 440971.038 | | ops/s
| BenchMark.generator | 1 | 2 | PLAIN | thrpt | 2| 565538.851 | | ops/s
| BenchMark.generator | 1 | 2 | TYPE_CONVERT | thrpt | 2| 229661.258 | | ops/s
| BenchMark.generator | 10 | 1 | PLAIN | thrpt | 2| 246582.733 | | ops/s
| BenchMark.generator | 10 | 1 | TYPE_CONVERT | thrpt | 2| 187783.255 | | ops/s
| BenchMark.generator | 10 | 2 | PLAIN | thrpt | 2| 127306.807 | | ops/s
| BenchMark.generator | 10 | 2 | TYPE_CONVERT | thrpt | 2| 95882.728 | | ops/s
| BenchMark.parser | 1 | 1 | PLAIN | thrpt | 2| 528407.928 | | ops/s
| BenchMark.parser | 1 | 1 | TYPE_CONVERT | thrpt | 2| 236501.349 | | ops/s
| BenchMark.parser | 1 | 2 | PLAIN | thrpt | 2| 271663.022 | | ops/s
| BenchMark.parser | 1 | 2 | TYPE_CONVERT | thrpt | 2| 121965.692 | | ops/s
| BenchMark.parser | 10 | 1 | PLAIN | thrpt | 2| 164080.482 | | ops/s
| BenchMark.parser | 10 | 1 | TYPE_CONVERT | thrpt | 2| 120036.437 | | ops/s
| BenchMark.parser | 10 | 2 | PLAIN | thrpt | 2| 84024.509 | | ops/s
| BenchMark.parser | 10 | 2 | TYPE_CONVERT | thrpt | 2| 60672.881 | | ops/s

### CODE REVIEW

**Comment by fforw** [comment]
If you want to introduce refactorings, I'd like to discuss their merits and certainly have more information than a one-liner commit message. You should document your git commits thoroughly in general for a good commit history.

For pull requests, they're even more vital.

**Comment by fforw** [comment]
Also please no bunching up lots of different concerns into one pull request.

**Comment by fforw** [comment]
If you're microbenchmarking things, ReflectAsmObjectSupport might be a thing worth looking at. The reflection overhead is considerable and seems a lot better with ReflectASM.

**Comment by jaroslawherod** [comment]
Hi, 

> why are my IDE files obsolete? Whom do they disturb?

The IDE files are ok when single person works at project. When there is more then it often generates unnecessary conflicts and it makes harder to import project. See example [gitignore](https://www.gitignore.io/api/java,maven,eclipse,intellij) for java.


> If you want to introduce refactorings, I'd like to discuss their merits and certainly have more information than a one-liner commit message. You should document your git commits thoroughly in general for a good commit history.
> 
> For pull requests, they're even more vital.


I see that too many commits were included into PR, sorry for that. I wanted to include only 2 first with introduce of method accessor's. As next I wanted to provide benchmarks for various implementations like :

- Reflection
- ReflectASM
- Method Handlers ( JDK 7+) 
- Lambda Handlers ( JDK 8+) 

I prefer approach `let the code speak` and I wanted to show the changes and then discuss it as part of PR review ( like we are doing it now ) 
> Also please no bunching up lots of different concerns into one pull request.

My bad. I will back off the PR and create new one.
I wanted to play with CircleCI or TravisCI to execute benchmarks I didn't expect that this will be included into PR.



> If you're microbenchmarking things, ReflectAsmObjectSupport might be a thing worth looking at. The reflection overhead is considerable and seems a lot better with ReflectASM.

I've already done some benchmarks. The results highly depends at JVM version.
It looks like the Reflection gives best performance at JVM 7.  Method Handles at JVM 7 gives 20% of Reflection performance.
At JVM 8, Reflection still gives best performance, Method Handles gives 95-100% of Reflections performance. 

See results ( It's first result after I've provided many changes and as far as I see it may have big error) : 
Legend :
- Benchmark 
  - generate - Generates json from already generated bean
  - parse  - Parse json string into object
- (framework) - Framework used to parse or generate json

  - SVENSON - svenson based implemntation
  - GSON - Gson based implemnetaion
- (items) - Number of items at lists in generated objects. Predefined objects always have two list with `Objects` and `primitive String` ( in sense of plain value)  
- (nested) - Objects can have nested structure ( one node tree), parameter defines the depth of nested objects.
- (methodAccess) - Defines the method access implementation

  - DEFAULT - For Svenson it's reflection. For Gson it's the only supported.
  - REFLECTASM 
  - METHOD_HANDLE
- (scenario) - Defines the test scenrio 
  - PLAIN - Plain objects without type convertions 
  - TYPE_CONVERT - Object with fields that needs type convert 

- Mode - Benchmark mode currently configured to use Throughput. 
- Cnt - Number of iterations ( currently each iteration takes 1 sec that's why it gives such big error) 
- Score - No need to explain. 
- Error - No need to explain.
- Units - No need to explain.



|Benchmark        |    (framework) | (items)|(methodAccess) | (nested)   | (scenario) |  Mode | Cnt   |  Score   |  Error |  Units|
| ---             |   ---          | ---    | ---           |   ---      |   ---      |  ---  | ---   |  ---     | ---    | ---   | 
| BenchMark.generator | GSON | 1 | DEFAULT | 1 | PLAIN | thrpt | 2| 1308.622 | ± 849.612 | ops/ms
| BenchMark.generator | GSON | 1 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 1461.124 | ± 580.204 | ops/ms
| BenchMark.generator | GSON | 1 | DEFAULT | 2 | PLAIN | thrpt | 2| 860.068 | ± 303.865 | ops/ms
| BenchMark.generator | GSON | 1 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 745.848 | ± 292.576 | ops/ms
| BenchMark.generator | GSON | 10 | DEFAULT | 1 | PLAIN | thrpt | 2| 401.114 | ± 170.678 | ops/ms
| BenchMark.generator | GSON | 10 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 336.976 | ± 530.440 | ops/ms
| BenchMark.generator | GSON | 10 | DEFAULT | 2 | PLAIN | thrpt | 2| 215.462 | ± 80.220 | ops/ms
| BenchMark.generator | GSON | 10 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 159.200 | ± 202.054 | ops/ms
| BenchMark.generator | SVENSON | 1 | DEFAULT | 1 | PLAIN | thrpt | 2| 1657.104 | ± 370.584 | ops/ms
| BenchMark.generator | SVENSON | 1 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 1585.240 | ± 297.132 | ops/ms
| BenchMark.generator | SVENSON | 1 | DEFAULT | 2 | PLAIN | thrpt | 2| 886.117 | ± 655.207 | ops/ms
| BenchMark.generator | SVENSON | 1 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 831.518 | ± 526.676 | ops/ms
| BenchMark.generator | SVENSON | 1 | METHOD_HANDLE | 1 | PLAIN | thrpt | 2| 113.857 | ± 95.013 | ops/ms
| BenchMark.generator | SVENSON | 1 | METHOD_HANDLE | 1 | TYPE_CONVERT | thrpt | 2| 131.554 | ± 33.658 | ops/ms
| BenchMark.generator | SVENSON | 1 | METHOD_HANDLE | 2 | PLAIN | thrpt | 2| 76.603 | ± 34.323 | ops/ms
| BenchMark.generator | SVENSON | 1 | METHOD_HANDLE | 2 | TYPE_CONVERT | thrpt | 2| 80.537 | ± 10.700 | ops/ms
| BenchMark.generator | SVENSON | 1 | REFLECTASM | 1 | PLAIN | thrpt | 2| 1354.192 | ± 623.533 | ops/ms
| BenchMark.generator | SVENSON | 1 | REFLECTASM | 1 | TYPE_CONVERT | thrpt | 2| 1478.856 | ± 109.472 | ops/ms
| BenchMark.generator | SVENSON | 1 | REFLECTASM | 2 | PLAIN | thrpt | 2| 884.218 | ± 199.381 | ops/ms
| BenchMark.generator | SVENSON | 1 | REFLECTASM | 2 | TYPE_CONVERT | thrpt | 2| 844.841 | ± 141.938 | ops/ms
| BenchMark.generator | SVENSON | 10 | DEFAULT | 1 | PLAIN | thrpt | 2| 424.496 | ± 90.645 | ops/ms
| BenchMark.generator | SVENSON | 10 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 386.626 | ± 76.171 | ops/ms
| BenchMark.generator | SVENSON | 10 | DEFAULT | 2 | PLAIN | thrpt | 2| 208.124 | ± 29.559 | ops/ms
| BenchMark.generator | SVENSON | 10 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 204.293 | ± 58.635 | ops/ms
| BenchMark.generator | SVENSON | 10 | METHOD_HANDLE | 1 | PLAIN | thrpt | 2| 33.612 | ± 2.408 | ops/ms
| BenchMark.generator | SVENSON | 10 | METHOD_HANDLE | 1 | TYPE_CONVERT | thrpt | 2| 32.674 | ± 2.454 | ops/ms
| BenchMark.generator | SVENSON | 10 | METHOD_HANDLE | 2 | PLAIN | thrpt | 2| 17.247 | ± 2.812 | ops/ms
| BenchMark.generator | SVENSON | 10 | METHOD_HANDLE | 2 | TYPE_CONVERT | thrpt | 2| 17.268 | ± 2.671 | ops/ms
| BenchMark.generator | SVENSON | 10 | REFLECTASM | 1 | PLAIN | thrpt | 2| 369.789 | ± 127.928 | ops/ms
| BenchMark.generator | SVENSON | 10 | REFLECTASM | 1 | TYPE_CONVERT | thrpt | 2| 382.340 | ± 23.445 | ops/ms
| BenchMark.generator | SVENSON | 10 | REFLECTASM | 2 | PLAIN | thrpt | 2| 196.470 | ± 20.216 | ops/ms
| BenchMark.generator | SVENSON | 10 | REFLECTASM | 2 | TYPE_CONVERT | thrpt | 2| 193.386 | ± 28.764 | ops/ms
| BenchMark.parser | GSON | 1 | DEFAULT | 1 | PLAIN | thrpt | 2| 2188.582 | ± 225.079 | ops/ms
| BenchMark.parser | GSON | 1 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 1872.490 | ± 337.714 | ops/ms
| BenchMark.parser | GSON | 1 | DEFAULT | 2 | PLAIN | thrpt | 2| 1315.734 | ± 54.810 | ops/ms
| BenchMark.parser | GSON | 1 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 1096.252 | ± 255.197 | ops/ms
| BenchMark.parser | GSON | 10 | DEFAULT | 1 | PLAIN | thrpt | 2| 694.471 | ± 893.692 | ops/ms
| BenchMark.parser | GSON | 10 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 655.141 | ± 397.360 | ops/ms
| BenchMark.parser | GSON | 10 | DEFAULT | 2 | PLAIN | thrpt | 2| 397.639 | ± 150.420 | ops/ms
| BenchMark.parser | GSON | 10 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 398.426 | ± 47.029 | ops/ms
| BenchMark.parser | SVENSON | 1 | DEFAULT | 1 | PLAIN | thrpt | 2| 931.741 | ± 102.383 | ops/ms
| BenchMark.parser | SVENSON | 1 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 844.783 | ± 85.558 | ops/ms
| BenchMark.parser | SVENSON | 1 | DEFAULT | 2 | PLAIN | thrpt | 2| 500.879 | ± 35.188 | ops/ms
| BenchMark.parser | SVENSON | 1 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 444.098 | ± 14.427 | ops/ms
| BenchMark.parser | SVENSON | 1 | METHOD_HANDLE | 1 | PLAIN | thrpt | 2| 240.842 | ± 44.268 | ops/ms
| BenchMark.parser | SVENSON | 1 | METHOD_HANDLE | 1 | TYPE_CONVERT | thrpt | 2| 209.753 | ± 18.661 | ops/ms
| BenchMark.parser | SVENSON | 1 | METHOD_HANDLE | 2 | PLAIN | thrpt | 2| 124.697 | ± 8.775 | ops/ms
| BenchMark.parser | SVENSON | 1 | METHOD_HANDLE | 2 | TYPE_CONVERT | thrpt | 2| 103.437 | ± 71.777 | ops/ms
| BenchMark.parser | SVENSON | 1 | REFLECTASM | 1 | PLAIN | thrpt | 2| 861.361 | ± 137.782 | ops/ms
| BenchMark.parser | SVENSON | 1 | REFLECTASM | 1 | TYPE_CONVERT | thrpt | 2| 796.803 | ± 125.555 | ops/ms
| BenchMark.parser | SVENSON | 1 | REFLECTASM | 2 | PLAIN | thrpt | 2| 474.273 | ± 65.493 | ops/ms
| BenchMark.parser | SVENSON | 1 | REFLECTASM | 2 | TYPE_CONVERT | thrpt | 2| 409.282 | ± 39.675 | ops/ms
| BenchMark.parser | SVENSON | 10 | DEFAULT | 1 | PLAIN | thrpt | 2| 281.976 | ± 23.838 | ops/ms
| BenchMark.parser | SVENSON | 10 | DEFAULT | 1 | TYPE_CONVERT | thrpt | 2| 271.568 | ± 25.279 | ops/ms
| BenchMark.parser | SVENSON | 10 | DEFAULT | 2 | PLAIN | thrpt | 2| 143.162 | ± 4.533 | ops/ms
| BenchMark.parser | SVENSON | 10 | DEFAULT | 2 | TYPE_CONVERT | thrpt | 2| 138.219 | ± 21.645 | ops/ms
| BenchMark.parser | SVENSON | 10 | METHOD_HANDLE | 1 | PLAIN | thrpt | 2| 87.082 | ± 3.908 | ops/ms
| BenchMark.parser | SVENSON | 10 | METHOD_HANDLE | 1 | TYPE_CONVERT | thrpt | 2| 80.190 | ± 6.737 | ops/ms
| BenchMark.parser | SVENSON | 10 | METHOD_HANDLE | 2 | PLAIN | thrpt | 2| 43.536 | ± 1.850 | ops/ms
| BenchMark.parser | SVENSON | 10 | METHOD_HANDLE | 2 | TYPE_CONVERT | thrpt | 2| 39.051 | ± 3.620 | ops/ms
| BenchMark.parser | SVENSON | 10 | REFLECTASM | 1 | PLAIN | thrpt | 2| 270.086 | ± 16.583 | ops/ms
| BenchMark.parser | SVENSON | 10 | REFLECTASM | 1 | TYPE_CONVERT | thrpt | 2| 255.229 | ± 68.286 | ops/ms
| BenchMark.parser | SVENSON | 10 | REFLECTASM | 2 | PLAIN | thrpt | 2| 139.328 | ± 11.162 | ops/ms
| BenchMark.parser | SVENSON | 10 | REFLECTASM | 2 | TYPE_CONVERT | thrpt | 2| 133.187 | ± 9.520 | ops/ms

**Pull request closed without merging**
